### ISSUE TITLE
Support PHP 8.4.1

### ISSUE THREAD

**Issue by lloydowen** [404labfr/laravel-impersonate#212] opened 2024-12-23 16:45 UTC
Since PHP 8.4.1 there are lots of deprecated warnings. Whilst they are only warnings we should look to fix them.
```
PHP Deprecated:  can_impersonate(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/*/vendor/lab404/laravel-impersonate/src/helpers.php on line 13

Deprecated: can_impersonate(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/*/vendor/lab404/laravel-impersonate/src/helpers.php on line 13
PHP Deprecated:  can_be_impersonated(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/*/vendor/lab404/laravel-impersonate/src/helpers.php on line 31

Deprecated: can_be_impersonated(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/*/vendor/lab404/laravel-impersonate/src/helpers.php on line 31
PHP Deprecated:  is_impersonating(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/*/vendor/lab404/laravel-impersonate/src/helpers.php on line 48

Deprecated: is_impersonating(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead in /Users/lloyd/Documents/work/clear/***/vendor/lab404/laravel-impersonate/src/helpers.php on line 48

```

I believe this is a fairly easy fix.

**Comment by drbyte** [comment] 2024-12-23 17:43
Looks like a duplicate of #211 and #209

**Closed** 2024-12-23 20:45 UTC
